CREATE TABLE note (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(200) NOT NULL CHECK (length(title) >= 3),
                      content VARCHAR(2000) NOT NULL
);